---
title: "Maps_T2"
author: "Santiago Maldonado Vizcarra"
date: "2024-04-17"
output: html_document
---

# Ejercicio N°1: 


Creamos el objeto 'MAPS' para facilitar el codeo: 


```{r}
MAPS = "C:/Users/LENOVO/OneDrive/Documentos/ASIE/introgeodf/maps/worldMap.gpkg"
```


Aquí se pasa a la revisión de las características de cada uno de los layers: 


```{r}
sf::st_layers(MAPS) # a link to github data
```


Pasamos a configurar los datos para la visualización gráfica: 


```{r}
countries=read_sf(MAPS,layer="countryBorders")
rivers=read_sf(MAPS,layer="riverLines")
cities=read_sf(MAPS,layer="cityPoints")
```

```{r}
library(ggplot2)
```


Visualización gráfica: 


```{r}
baseLayer=ggplot(data=countries)  + geom_sf(fill='bisque2') + theme_light()
final=baseLayer + geom_sf(data=rivers, color='blue') + geom_sf(data=cities, color='lightgreen') 
final
```


# Ejercicio N°2

```{r}
peru <- countries[countries$COUNTRY == 'Peru', ]
peru_rivers <- rivers[rivers$SYSTEM == 'Peru', ]
peru_cities <- cities [cities$COUNTRY == 'Peru', ]
```


```{r}
baseLayer=ggplot(data=peru)  + geom_sf(fill='grey90') + theme_light()
final=baseLayer + geom_sf(data=peru_rivers, color='blue') + geom_sf(data=peru_cities, color='red') 
final
```










